version: "3.7"
services:
    app:
        build:
            args:
                user: maftuna
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: product
        container_name: product-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - product
    db:
        image: postgres:latest
        container_name: product-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - .:/docker-entrypoint-initdb.d
        ports:
            - "5433:5432"
        networks:
            - product
    nginx:
        image: nginx:1.17-alpine
        container_name: product-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - product

networks:
    product:
        driver: bridge
